# Generated by Django 5.0.1 on 2024-01-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_flavour_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Categories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filter_price',
        ),
        migrations.RemoveField(
            model_name='images',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Subcategories',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='information',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Filter_Price',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Subcategories',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
