# Generated by Django 5.0.1 on 2024-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_item_categories_remove_item_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=300)),
                ('confirmpass', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
