# Generated by Django 5.0.1 on 2024-01-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
