# Generated by Django 5.0.1 on 2024-01-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Registration',
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
