# Generated by Django 5.0.1 on 2024-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_userprofile_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
