# Generated by Django 5.0.1 on 2024-02-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_category_filter_price_flavours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
