# Generated by Django 5.0.1 on 2024-02-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_alter_filter_price_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavours',
            new_name='Flavour',
        ),
    ]
