# Generated by Django 5.0.1 on 2024-02-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_rename_flavours_flavour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
