# Generated by Django 5.0.1 on 2024-02-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contact_us',
        ),
    ]
