# Generated by Django 5.0.1 on 2024-02-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_rename_contact_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.DecimalField(choices=[('200 To 500', '200 To 500'), ('500 To 1000', '500 To 1000'), ('1000 To 1500', '1000 To 1500'), ('1500 To 2000', '1500 To 2000')], decimal_places=2, max_digits=10),
        ),
    ]
