# Generated by Django 5.0.1 on 2024-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_rename_reviewratind_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
