# Generated by Django 5.0.1 on 2024-02-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0035_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='itm',
            new_name='item',
        ),
    ]
