# Generated by Django 5.0.1 on 2024-02-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0036_rename_itm_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
