# Generated by Django 5.0.1 on 2024-02-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0037_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='username',
        ),
    ]
