# Generated by Django 5.0.1 on 2024-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0038_rename_firstname_order_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creditcard_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameon_card',
        ),
    ]
