# Generated by Django 5.0.1 on 2024-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0042_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
