# Generated by Django 5.0.1 on 2024-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0047_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
