# Generated by Django 5.0.1 on 2024-02-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0059_alter_order_amount_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
