# Generated by Django 5.0.1 on 2024-02-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0069_remove_orderitem_user_alter_item_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
