# Generated by Django 5.0.1 on 2024-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0074_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
