# Generated by Django 5.0.1 on 2024-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0077_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('10 To 200', '10 To 200'), ('200 To 500', '200 To 500'), ('500 To 1000', '500 To 1000'), ('1000 To 1500', '1000 To 1500'), ('1500 To 2000', '1500 To 2000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(default=100, max_length=100, null=True),
        ),
    ]
