# Generated by Django 5.0.1 on 2024-02-20 08:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0079_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
