# Generated by Django 5.0.1 on 2024-02-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0083_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_id',
            new_name='unique_id',
        ),
    ]
