# Generated by Django 5.0.1 on 2024-02-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0084_rename_cust_id_customer_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='unique_id',
            new_name='cust_id',
        ),
    ]
