# Generated by Django 5.0.1 on 2024-02-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0085_rename_unique_id_customer_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
