# Generated by Django 5.0.1 on 2024-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0091_remove_profile_address_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cust',
        ),
    ]
