# Generated by Django 5.0.1 on 2024-03-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0092_delete_cust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
