# Generated by Django 5.0.1 on 2024-03-23 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0095_alter_order_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
