# Generated by Django 5.0.1 on 2024-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0098_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
