# Generated by Django 5.0.1 on 2024-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0099_rename_phone_number_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='process',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROCESS', 'IN PROCESS'), ('MADE', 'MADE')], default='PENDING', max_length=200),
        ),
    ]
