# Generated by Django 5.0.3 on 2024-07-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0104_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
